GRANT DELETE, INSERT, SELECT, UPDATE, USAGE, CREATE, DROP, ALTER, INDEX, LOCK TABLES ON db_spexregister_prod.* TO spex@localhost IDENTIFIED BY 'spex';
GRANT DELETE, INSERT, SELECT, UPDATE, USAGE, CREATE, DROP, ALTER, INDEX, LOCK TABLES ON db_spexregister_prod.* TO spex@127.0.0.1 IDENTIFIED BY 'spex';
