development: &defaults
  entities_per_page: 10
  latest_news_per_page: 8
  activities_per_row: 3
  # In Kb
  max_upload_size: 150
  allowed_file_types: image/jpg,image/jpeg,image/pjpeg,image/gif,image/png,image/x-png
  poster_thumbnail_size: 50x70>
  picture_thumbnail_size: 50x70>
  logo_thumbnail_size: 50x70>
  logged_in_timeout: <%= 60.minutes.to_i %> 
  remember_me_for: <%= 3.months.to_i %>
  consecutive_failed_logins_limit: 5
  failed_login_ban_for: <%= 2.hours.to_i %>
  first_fgv_year: 1987
  first_cing_year: 1907
  default_country: 'SE'
  google_analytics_account_id: 'UA-35742612-1'
test:
  <<: *defaults
production:
  <<: *defaults
