development: &defaults
  app_version: 0.0.4
  site_url: www.chalmersspexet.se/register
  admin_mail_address: register@chalmersspexet.com
  default_listing_page_size: 10
  related_spexare_dropdown_list_size: 12
  spexare_dropdown_list_size: 15
  paginator_window_size: 5
  export_page_size: 25
  # In Kb
  max_upload_size: 150
  allowed_file_types: image/jpg,image/jpeg,image/pjpeg,image/gif,image/png,image/x-png
  poster_thumbnail_size: 50x70>
  picture_thumbnail_size: 50x70>
  logged_in_timeout: <%= 60.minutes.to_i %> 
  remember_me_for: <%= 3.months.to_i %>
  consecutive_failed_logins_limit: 5
  failed_login_ban_for: <%= 2.hours.to_i %>
test:
  <<: *defaults
production:
  <<: *defaults
