--- 
javascripts:
- base:
  - jquery
  - jquery-ui
  - jquery.suggest
  - jquery.validate
  - jquery.alerts
  - jquery.lightbox
  - jrails
  - jrails.autocomplete
  - datepicker/datepicker
  - spexregister
stylesheets:
- screen:
  - compiled/screen
  - jquery.alerts
  - jquery.lightbox
  - datepicker
- ie:
  - compiled/ie
- print:
  - compiled/print
