--- 
javascripts:
- base:
  - jquery
  - jquery-ui
  - jquery.suggest
  - jquery.validate
  - jquery.alerts
  - jquery.fancybox
  - jquery.datepicker
  - jquery.livequery
  - jquery.lockSubmit
  - jquery.checkbox
  - jquery.multiselect
  - jrails
  - jrails.autocomplete
  - spexregister
stylesheets:
- screen:
  - jquery.core
  - jquery.alerts
  - jquery.fancybox
  - jquery.datepicker
  - jquery.checkbox
  - jquery.multiselect
  - jquery.flick.theme
  - compiled/screen
- ie:
  - compiled/ie
- print:
  - compiled/print
