--- 
javascripts:
- base:
  - jquery
  - jquery-ui
  - jquery.suggest
  - jquery.alerts
  - jquery.fancybox
  - jquery.datepicker
  - jquery.cookie
  - jquery.livequery
  - jquery.uniform
  - jquery.selectboxes
  - jquery.colorhelpers
  - jquery.flot
  - jquery.flot.crosshair
  - jquery.flot.navigate
  - jquery.flot.selection
  - jquery.flot.stack
  - jquery.flot.threshold
  - jquery.flot.fillbetween
  - jquery.flot.pie
  - jquery.flot.image
  - jquery.flot.symbol
  - jquery.fg.menu
  - jrails
  - jrails.autocomplete
  - spexregister
- ie:
  - excanvas
stylesheets:
- screen:
  - jquery.core
  - jquery.alerts
  - jquery.fancybox
  - jquery.datepicker
  - jquery.uniform
  - jquery.flick.theme
  - jquery.fg.menu
  - compiled/screen
- ie:
  - compiled/ie
- print:
  - compiled/print
