--- 
javascripts: 
- base: 
  - jquery
  - jquery-ui
  - jquery.suggest
  - jrails
  - jrails.autocomplete
  - spexregister
stylesheets: 
- screen: 
  - compiled/screen
- ie:
  - compiled/ie
- print:
  - compiled/print
