namespace :deploy do
  desc 'Create asset packages for production'
  task :package_assets, :roles => :app do
    run <<-EOF
      cd #{deploy_to}/current && rake RAILS_ENV=production asset:packager:build_all
    EOF
  end
end

namespace :sass do
  desc 'Updates the stylesheets generated by Sass'
  task :update do
    run "cd #{current_path} && rake sass:update"
  end
end

after  'deploy:symlink', 'deploy:package_assets'
before 'deploy:package_assets', 'sass:update'
