class InsertFunctionItems < ActiveRecord::Migration
  def self.up
    down
    
    FunctionItem.create :name => 'Affisch', :function_category_item => FunctionCategoryItem.find_by_category_name('Annat')
    FunctionItem.create :name => 'Altsaxofon', :function_category_item => FunctionCategoryItem.find_by_category_name('Bandet')
    FunctionItem.create :name => 'Arkitekt', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Arrangör', :function_category_item => FunctionCategoryItem.find_by_category_name('Annat')
    FunctionItem.create :name => 'Bas', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Bas', :function_category_item => FunctionCategoryItem.find_by_category_name('Bandet')
    FunctionItem.create :name => 'Basklarinett', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Bastuba', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Blockflöjt', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Casseur', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Cello', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Cello 1', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Cello 2', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Dekoratör', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Designer', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Directeur', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Directeursassistent', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Elfiol', :function_category_item => FunctionCategoryItem.find_by_category_name('Bandet')
    FunctionItem.create :name => 'Ensemble', :function_category_item => FunctionCategoryItem.find_by_category_name('Ensemble')
    FunctionItem.create :name => 'Exspextor', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Fagott', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Festdirecteur', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Festroddare', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Flöjt', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Fotografiker', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Författare', :function_category_item => FunctionCategoryItem.find_by_category_name('Annat')
    FunctionItem.create :name => 'Gitarr', :function_category_item => FunctionCategoryItem.find_by_category_name('Bandet')
    FunctionItem.create :name => 'Horn', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Info-chef', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Inspextor', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Inspextris', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Inspicient', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Inspicientassistent', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Kapellmästare', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Klarinett', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Klarinett', :function_category_item => FunctionCategoryItem.find_by_category_name('Bandet')
    FunctionItem.create :name => 'Kommittéledamot', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Kontrabas', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Ljudmästare', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Ljusmästare', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Ljudroddare', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Ljusroddare', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Mediamästare', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Musikproducent', :function_category_item => FunctionCategoryItem.find_by_category_name('Annat')
    FunctionItem.create :name => 'Oboe', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Oboeflöjt', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Okänt', :function_category_item => FunctionCategoryItem.find_by_category_name('Annat')
    FunctionItem.create :name => 'Okänt', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Okänt', :function_category_item => FunctionCategoryItem.find_by_category_name('Bandet')
    FunctionItem.create :name => 'Organisateur', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Orkester', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'PR-chef', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'PR/Info-stab', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Panblåsare', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Pianör', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Pianör', :function_category_item => FunctionCategoryItem.find_by_category_name('Bandet')
    FunctionItem.create :name => 'Producent', :function_category_item => FunctionCategoryItem.find_by_category_name('Annat')
    FunctionItem.create :name => 'Regisseur', :function_category_item => FunctionCategoryItem.find_by_category_name('Annat')
    FunctionItem.create :name => 'Saxofon', :function_category_item => FunctionCategoryItem.find_by_category_name('Bandet')
    FunctionItem.create :name => 'Saxofon', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Scen', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Scenmästare', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Scenograf', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Scenroddare', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Sekreterare', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Skivkommitté', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Skräddare', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Slagverk', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Sopransaxofon', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Sufflör', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Sömmerska', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Tenorsaxofon', :function_category_item => FunctionCategoryItem.find_by_category_name('Bandet')
    FunctionItem.create :name => 'Trombon', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Trummor', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Trummor', :function_category_item => FunctionCategoryItem.find_by_category_name('Bandet')
    FunctionItem.create :name => 'Trumpet', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Trumpet', :function_category_item => FunctionCategoryItem.find_by_category_name('Bandet')
    FunctionItem.create :name => 'Tvärflöjt', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Upplysare', :function_category_item => FunctionCategoryItem.find_by_category_name('Kommitté')
    FunctionItem.create :name => 'Valthorn', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Viola', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Violacello', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Violin', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Violin 1', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Violin 2', :function_category_item => FunctionCategoryItem.find_by_category_name('Orkester')
    FunctionItem.create :name => 'Vistextförfattare', :function_category_item => FunctionCategoryItem.find_by_category_name('Annat')
  end

  def self.down
    FunctionItem.delete_all
  end
end
