class InsertSpexItems < ActiveRecord::Migration
  def self.up
    down
    
    SpexItem.create :year => '1948', :title => 'Bojan', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1949', :title => 'Erik XIV', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1950', :title => 'Ceasarion', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1951', :title => 'Scheherazade', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1952', :title => 'Anna', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1953', :title => 'Ceasarion', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1954', :title => 'Henrik VIII', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1955', :title => 'Gustav E:son Vasa', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1956', :title => 'Napoleon', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1957', :title => 'Statyerna', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1958', :title => 'Lucrezia', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1959', :title => 'Katarina II', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1960', :title => 'Starke August', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1961', :title => 'Klodvig', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1962', :title => 'Don Pedro', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1963', :title => 'Charles II', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1964', :title => 'Nebukadnessar', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1965', :title => 'Sven Duva', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1966', :title => 'Montezuma', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1967', :title => 'Alexander', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1968', :title => 'Richard III', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1969', :title => 'Margareta', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1970', :title => 'George Washington', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1971', :title => 'Noak', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1972', :title => 'Turandot', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1973', :title => 'Fredrik den Store', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1974', :title => 'Sherlock Holmes', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1975', :title => 'Lionardo da Vinci', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1976', :title => 'Ludvig XIV', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1977', :title => 'Nils Dacke', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1978', :title => 'Dr Livingstone', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1979', :title => 'Nero', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1979', :title => 'Knappt ett Chalmersspex', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1980', :title => 'Tutankhamon', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1981', :title => 'Ludwig van Beethoven', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1982', :title => 'John Ericsson', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1983', :title => 'Filip II', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1984', :title => 'Lasse-Maja', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1985', :title => 'Olof Skötkonung', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1986', :title => 'Victoria', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1987', :title => 'Montgomery', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1988', :title => 'Svartskägg', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1989', :title => 'Christina', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1990', :title => 'Klondike', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1991', :title => 'Gutenberg', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1992', :title => 'Krösus', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1993', :title => 'Stradivarius', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1994', :title => 'Ivan den förskräcklige', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1995', :title => 'Snorre', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1996', :title => 'Nobel', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1997', :title => 'Ali Baba', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1998', :title => 'Sköna Hélena', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '1999', :title => 'Nostradamus', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '2000', :title => 'Mose', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '2001', :title => 'Marco Polo', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '2002', :title => 'Dracula', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '2003', :title => 'Gagarin', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '2003', :title => 'Mata Hari', :spex_category_item => SpexCategoryItem.find_by_category_name('Vera')
    SpexItem.create :year => '2004', :title => 'Heliga Birgitta', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '2004', :title => 'Phileas Fogg', :spex_category_item => SpexCategoryItem.find_by_category_name('Vera')
    SpexItem.create :year => '2005', :title => 'Gustav II Adolf', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '2005', :title => 'Arthur', :spex_category_item => SpexCategoryItem.find_by_category_name('Vera')
    SpexItem.create :year => '2006', :title => 'Casanova', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
    SpexItem.create :year => '2006', :title => 'Amelia Earhart', :spex_category_item => SpexCategoryItem.find_by_category_name('Vera')
    SpexItem.create :year => '2007', :title => 'Hannibal', :spex_category_item => SpexCategoryItem.find_by_category_name('Bob')
  end

  def self.down
    SpexItem.delete_all
  end
end
